version: '3'
services:
  prometheus:
    build: ./prometheus/
    network_mode: "host"
    volumes:
      - prometheus_volume:/prometheus
  #grafana:
  #  build: ./grafana/
  #  network_mode: "host"
volumes:
  prometheus_volume:
    driver: local
